contracts/JBERC20PaymentTerminal3_2.sol
contracts/JBETHPaymentTerminal3_2.sol
contracts/JBPrices3_2.sol
contracts/JBSingleTokenPaymentTerminalStore3_2.sol
contracts/abstract/JBPayoutRedemptionPaymentTerminal3_2.sol
contracts/interfaces/IJBPayoutRedemptionPaymentTerminal3_2.sol
contracts/interfaces/IJBPrices3_2.sol
contracts/interfaces/IJBSingleTokenPaymentTerminalStore3_2.sol
contracts/libraries/JBOperations2.sol

working on permit2 tests but making sure this looks right

Merge #4 into #5 + Permit2 tests

---

contracts/JBSingleTokenPaymentTerminalStore3_2.sol
contracts/abstract/JBPayoutRedemptionPaymentTerminal3_2.sol
contracts/interfaces/IJBFundingCycleDataSource3_2.sol
contracts/interfaces/IJBPayDelegate3_2.sol
contracts/interfaces/IJBPayoutRedemptionPaymentTerminal3_2.sol
contracts/interfaces/IJBRedemptionDelegate3_2.sol
contracts/interfaces/IJBSingleTokenPaymentTerminalStore3_1_1.sol
contracts/interfaces/IJBSingleTokenPaymentTerminalStore3_2.sol
contracts/structs/JBDidPayData3_2.sol
contracts/structs/JBDidRedeemData3_2.sol
contracts/structs/JBPayDelegateAllocation3_2.sol
contracts/structs/JBRedemptionDelegateAllocation3_2.sol

added a few relevant context (take 2)

---

.github/pull_request_template.md
.gitignore
foundry.toml
package.json

- Align yarn package.json and foundry.toml with JB protocol repo
- Modify yarn scripts to put main on forge test & deployment
- Add PR template
- Add coverage and yarn error to gitignore

fix: yarn and foundry config files

---

.gitmodules
contracts/JBController.sol
contracts/JBMultiTerminal.sol
contracts/JBPrices.sol
contracts/JBRulesets.sol
contracts/JBTerminalStore.sol
contracts/interfaces/terminal/IJBPermitTerminal.sol
contracts/libraries/JBFees.sol
forge_tests/TestAccessToFunds.sol
forge_tests/TestMetaTx.sol
forge_tests/TestMultipleAccessLimits.sol
forge_tests/TestPayBurnRedeemFlow.sol
forge_tests/TestPayHooks.sol
forge_tests/TestPermit2Terminal.sol
forge_tests/TestRedeem.sol
forge_tests/TestRedeemHooks.sol
forge_tests/TestSplits.sol
forge_tests/helpers/TestBaseWorkflow.sol
remappings.txt
script/Deploy.s.sol

For merging into #53 when done!
lfjjj, not a Node package in sight haha!

chore: update forge remappings

---

src/JBMultiTerminal.sol

fix: allow unlimited allowance

---

src/JBMultiTerminal.sol
src/interfaces/terminal/IJBFeeTerminal.sol

process held fees on migrate

---

src/JBController.sol
src/JBFundAccessLimits.sol
src/JBMultiTerminal.sol
src/JBPermissions.sol
src/libraries/JBConstants.sol

small changes for clarity and efficiency

---

src/interfaces/IJBPermissions.sol

interface touchp

---

src/JBController.sol
src/JBMultiTerminal.sol
src/JBSplits.sol
src/interfaces/IJBController.sol
src/interfaces/IJBSplits.sol
src/interfaces/terminal/IJBPayoutTerminal.sol

changed domain to rulesetId

---

src/JBController.sol
src/JBDirectory.sol
src/JBMultiTerminal.sol
src/JBPermissions.sol
src/JBPrices.sol
src/abstract/JBPermissioned.sol

requirePermissionFrom

---

src/JBMultiTerminal.sol
src/JBTerminalStore.sol
src/interfaces/IJBTerminalStore.sol
src/interfaces/terminal/IJBPayoutTerminal.sol
src/interfaces/terminal/IJBRedeemTerminal.sol
src/structs/JBDidRedeemData.sol
src/structs/JBRedeemParamsData.sol
test/TestAccessToFunds.sol
test/TestFees.sol
test/TestMultipleAccessLimits.sol
test/TestPayBurnRedeemFlow.sol
test/TestRedeem.sol
test/TestRedeemHooks.sol
test/TestSplits.sol

redeem param name adjust

---

src/JBController.sol
src/JBMultiTerminal.sol
src/JBTerminalStore.sol

rm scoped sections

---

src/JBController.sol
src/interfaces/IJBController.sol
src/interfaces/IJBProjectMetadataRegistry.sol
src/interfaces/IJBProjectUriRegistry.sol
test/TestAccessToFunds.sol
test/TestFees.sol
test/TestLaunchProject.sol
test/TestMetaTx.sol
test/TestMintTokensOf.sol
test/TestMultipleAccessLimits.sol
test/TestPayBurnRedeemFlow.sol
test/TestPayHooks.sol
test/TestPermissions.sol
test/TestPermit2Terminal.sol
test/TestRedeem.sol
test/TestRedeemHooks.sol
test/TestRulesetQueueing.sol
test/TestRulesetWeightCaching.sol
test/TestSplits.sol
test/TestTokenFlow.sol

`projectMetadata` => `projectUri`
- Directly:
- Indirectly:

projectMetadata => projectUri

---

src/JBController.sol
src/JBRulesets.sol

Language touchups for #92 and #93.

fix: language touchups for project URI and rulesetsOf

---

src/JBController.sol
src/JBDirectory.sol
src/JBFundAccessLimits.sol
src/JBMultiTerminal.sol
src/JBPermissions.sol
src/JBRulesets.sol
src/JBSplits.sol
src/JBTerminalStore.sol

moved privates to internals

---

src/JBController.sol
src/interfaces/IJBController.sol

Reserved token's that are split to a projectId will be paid to the project instead of being sent to the project owner.
- Directly:
- Indirectly:

reserved token distro tries to pay project

---

src/JBController.sol
test/TestSplits.sol

try/catch logic when paying RR tokens to a terminal, no longer manually have to reset the allowance.
- Directly:
- Indirectly:

refactor: try/catch logic when paying RR tokens to a terminal

---

test/TestRulesetQueueing.sol
test/TestSplits.sol

retro ruleset queueing test

---

.vscode/settings.json
README.md
package.json

1. Remove `.vscode`
2. Make `npm run coverage` work (remove the match path).
3. Add README note for coverage in gutters + fixing LSP errors.

Misc. development touchups

---

.github/workflows/slither.yml
.github/workflows/test.yml
README.md
package-lock.json
package.json

fix: ci npm and slither issues

---

src/JBPermissions.sol
test/TestPermissions.sol

Before: 
| src/JBPermissions.sol:JBPermissions contract |                 |        |        |        |         |
|----------------------------------------------|-----------------|--------|--------|--------|---------|
| Deployment Cost                              | Deployment Size |        |        |        |         |
| 478134                                       | 2032            |        |        |        |         |
| Function Name                                | min             | avg    | median | max    | # calls |
| hasPermission                                | 929             | 944    | 929    | 2929   | 258     |
| hasPermissions                               | 1199            | 2844   | 1707   | 17402  | 256     |
| setPermissionsFor                            | 29330 …

refactor: optimize `JBPermissions` gas usage

---

.github/workflows/publish.yml

fix: publish to npm action

---

src/JBTokens.sol

fix: resolved an theoretical low impact reentrency although was not a vulnerability in its current state

---

README.md
package-lock.json
package.json
src/JBChainlinkV3PriceFeed.sol
src/JBController.sol
src/JBDeadline.sol
src/JBDirectory.sol
src/JBERC20.sol
src/JBFeelessAddresses.sol
src/JBFundAccessLimits.sol
src/JBMultiTerminal.sol
src/JBProjects.sol
src/interfaces/IJBRulesetApprovalHook.sol
test/helpers/MetadataResolverHelper.sol
test/units/static/JBController/TestDeployErc20For.sol
test/units/static/JBController/TestLaunchRulesetsFor.sol
test/units/static/JBController/TestSetSplitGroupsOf.sol
test/units/static/JBController/TestTransferCreditsFrom.sol
utils/unused-imports.sh

Pre audit touchups

---

.example.env
foundry.toml
script/Deploy.s.sol

feat: arb testnet deploys WIP

---

src/libraries/JBRulesetMetadataResolver.sol
test/units/static/JBRulesetMetadataResolver/TestSetRedemptionRateTo.sol

rm unused fn

---

src/JBProjects.sol

Removing ERC721Votes as recommended by Jango
Audit mitigation
- Directly:
- Indirectly:

33Audits [H-02] ERC721Votes

---

test/TestJBERC20Inheritance.sol

test: add test for `C-02`

---

package.json
script/helpers/CoreDeploymentLib.sol

ci: bump npm version, modified deployment helper

---

src/JBController.sol
src/JBTokens.sol

resolves https://github.com/Enigma-Dark/nana-core/issues/22

resolve Enigma-Dark audit issue #22

---

src/libraries/JBMetadataResolver.sol
test/TestMetadataParserLib.sol

metadata rounding fix- audit finding 19

---

package.json

ci: `v0.0.23`

---

slither-ci.config.json
src/JBChainlinkV3PriceFeed.sol
src/JBChainlinkV3SequencerPriceFeed.sol
src/JBController.sol
src/JBDeadline.sol
src/JBDirectory.sol
src/JBERC20.sol
src/JBMultiTerminal.sol
src/JBPrices.sol
src/JBProjects.sol
src/JBRulesets.sol
src/JBSplits.sol
src/JBTerminalStore.sol
src/JBTokens.sol
src/interfaces/IJBSplits.sol
test/units/static/JBMultiTerminal/TestPay.sol

fixed some slither errors

---

src/JBController.sol
src/JBRulesets.sol
src/JBTerminalStore.sol
src/interfaces/IJBController.sol
src/interfaces/IJBRulesetDataHook.sol
src/interfaces/IJBRulesets.sol
test/TestAccessToFunds.sol
test/TestSplits.sol
test/units/static/JBTerminalStore/TestCurrentReclaimableSurplusOf.sol
test/units/static/JBTerminalStore/TestCurrentSurplusOf.sol
test/units/static/JBTerminalStore/TestRecordPayoutFor.sol
test/units/static/JBTerminalStore/TestRecordRedemptionFor.sol
test/units/static/JBTerminalStore/TestRecordTerminalMigration.sol
test/units/static/JBTerminalStore/TestRecordUsedAllowanceOf.sol

rm reentrency in store
- Directly:
- Indirectly:

rm reentrnecy

---

package.json
script/DeployPeriphery.sol
src/JBChainlinkV3PriceFeed.sol
src/periphery/JBDeadline3Days.sol
src/periphery/JBDeadline7Days.sol

…eployment script
- Directly:
- Indirectly:

feat: add periphery

---

test/TestAccessToFunds.sol
test/mock/MockMaliciousBeneficiary.sol
test/units/static/JBTerminalStore/TestRecordUsedAllowanceOf.sol

Tests for new sendPayoutsOf & useAllowanceOf

---

src/JBFundAccessLimits.sol
src/JBRulesets.sol
src/interfaces/IJBRulesets.sol
test/TestMetadataParserLib.sol
test/TestRulesetQueueing.sol
test/helpers/JBTest.sol
test/units/static/JBController/TestDeployErc20For.sol
test/units/static/JBController/TestSendReservedTokensToSplitsOf.sol
test/units/static/JBMultiTerminal/TestAddAccountingContextsFor.sol
test/units/static/JBMultiTerminal/TestSendPayoutsOf.sol
test/units/static/JBRulesets/TestRulesets.sol

Iterating on coverage

---

.github/workflows/publish.yml

fix/ci: set publish workflow node version

---

src/JBMultiTerminal.sol
test/TestFees.sol

fix: wrong `amount` when processing held fees

---

src/JBMultiTerminal.sol
test/units/static/JBMultiTerminal/TestSendPayoutsOf.sol

dont take fees from failed payout

---

src/JBMultiTerminal.sol
src/interfaces/IJBFeeTerminal.sol
test/TestFees.sol
test/units/static/JBMultiTerminal/TestAddToBalanceOf.sol
test/units/static/JBMultiTerminal/TestMigrateBalanceOf.sol

limit number of held fees allowed.
- Directly:
- Indirectly:

added max number of held fees allowed

---

src/JBMultiTerminal.sol

verbose fn calls for clarity
- Directly:
- Indirectly:

verbose fn call

---

src/JBMultiTerminal.sol
src/JBTerminalStore.sol
src/libraries/JBCashOuts.sol
test/TestCashOutHooks.sol
test/TestMetaTx.sol
test/units/static/JBTerminalStore/TestCurrentReclaimableSurplusOf.sol
test/units/static/JBTerminalStore/TestRecordCashOutsFor.sol

reverse cashOutTax logic

---

test/units/static/JBMultiTerminal/TestSendPayoutsOf.sol

payout test fix, partial emit wen

---

src/JBChainlinkV3SequencerPriceFeed.sol
test/units/static/JBMultiTerminal/TestSendPayoutsOf.sol

Cantina/59 - Sequencer feed invalid round & Fix test error

---

src/JBSplits.sol

Fix: `JBSplit`  packing

---

src/libraries/JBCurrencyIds.sol
test/TestMultipleAccessLimits.sol

eth currency

---

script/DeployPeriphery.s.sol
src/JBChainlinkV3SequencerPriceFeed.sol
test/units/static/JBFeelessAdresses/TestSetFeelessAddress.sol

feat: L2 sequencer feed

---

script/DeployController4_1.s.sol

ci: set deployment address for OmnichainDeployer in the deployment script

---

package.json
script/DeployController4_1.s.sol

ci: modify deployment script

---

package.json

ci: version 1.0.6

---

package.json
script/DeployUSDCFeeds.s.sol

feat: added deployment script for USDC price feeds
